### ISSUE TITLE
Explore

### ISSUE THREAD

**Issue by SaraPiccolomini** [SaraPiccolomini/Visualeyed#13]
- [x] Font Date Picker non allineato con quello del sito

- [x] bug sul dropdown degli autori
<img width="440" alt="Schermata 2020-10-23 alle 16 40 51" src="https://user-images.githubusercontent.com/36152555/97017729-91a3de00-154e-11eb-8071-b8b68c1ced80.png">

- [x] Le chips con i tag sono draggabili e si navigano orizzontalmente
<img width="1893" alt="Schermata 2020-10-23 alle 16 42 07" src="https://user-images.githubusercontent.com/36152555/97017964-d9c30080-154e-11eb-9d45-c627936988b1.png">

- [x] una volta fatta una selezione lo specchietto tools resta aperto e mostra la selezione fatta (stato del bottone selected da allineare all'invision)
<img width="1890" alt="Schermata 2020-10-23 alle 16 44 53" src="https://user-images.githubusercontent.com/36152555/97018658-b2b8fe80-154f-11eb-8f9c-b5179fe03fed.png">

- [x] testo e icona nel campo dell'explore da allineare allo Zeplin
<img width="1480" alt="Schermata 2020-10-23 alle 16 47 21" src="https://user-images.githubusercontent.com/36152555/97018561-91f0a900-154f-11eb-9823-5369a240ed64.png">

**Comment by francescocusmai** [comment]
"bug sul dropdown degli autori"

Non è un bug è il comportamento standard del dropdown di bootstrap. Se così non va bene dobbiamo pensare a qualche soluzione alternativa. Potremmo ad esempio trattare gli autori in maniera simile ai tag. Fammi sapere.

**Comment by SaraPiccolomini** [comment]
Non è possibile dare un'altezza max al dropdown aperto e scrollare la lista dentro al dropdown?

Se questo non è possibile va bene anche la soluzione che proponete di trattare gli autori in modo simile ai tag! 
Possiamo aggiungere tra Filter e Tags una voce che è Author e di fianco le chips scrollabili orizzontalmente con tutte le testate (nota: anche "originals" va tra la lista degli autori e raccoglie v story, d story e editors review)

**Comment by francescocusmai** [comment]
Ho fatto come mi hai detto: ho aggiunto un'altezza massima al dropdown e aggiunto lo scroll

**Comment by francescocusmai** [comment]
"Le chips con i tag sono draggabili e si navigano orizzontalmente"

Sistemato, ma non si riesce a fare esattamente come lo hai disegnato (fluido solo a destra) resta confinato nella griglia

<img width="1243" alt="Schermata 2020-10-27 alle 11 21 07" src="https://user-images.githubusercontent.com/73244274/97289079-ff018880-1846-11eb-926a-726108a484ba.png">
