### ISSUE TITLE
D-Story

### ISSUE THREAD

**Issue by SaraPiccolomini** [SaraPiccolomini/Visualeyed#4]
- [x] Formattazione testo "D-story" (aumentare kerning) e bottone read (padding uguale a dx sx)
<img width="1573" alt="Schermata 2020-10-23 alle 14 59 52" src="https://user-images.githubusercontent.com/36152555/97006833-ba24db80-1540-11eb-924b-b00dfd2f9595.png">

- [x] le card dovrebbero avere sempre un formato quadrato sia nella landing che nella pagina Dstory
<img width="1871" alt="Schermata 2020-10-23 alle 15 05 30" src="https://user-images.githubusercontent.com/36152555/97007688-12101200-1542-11eb-9475-e9000fb20a12.png">

- [x] pagina aggregazione D-Story > card equidistanti tra loro 
<img width="1616" alt="Schermata 2020-10-23 alle 15 13 03" src="https://user-images.githubusercontent.com/36152555/97007904-674c2380-1542-11eb-8d93-8709031526b4.png">

**Comment by francescocusmai** [comment]
"le card dovrebbero avere sempre un formato quadrato sia nella landing che nella pagina Dstory"

Se vuoi posso forzare in modo che il box risulti sempre quadrato, ma lo sconsiglio poiché quando si ridimensiona lo schermo il testo potrebbe non starci più. In alternativa si può fissare un altezza minima per ciascun breakpoint in modo che il box non risulti mai eccessivamente rettangolare ma all’occorrenza è libero di adattarsi al contenuto. Fammi sapere come preferisci procedere.

**Comment by SaraPiccolomini** [comment]
Va bene mettiamo un'altezza minima per dare una forma più "quadrata" lasciando comunque la possibilità al box di adattarsi al contenuto, grazie!
