### ISSUE TITLE
Editor's Review

### ISSUE THREAD

**Issue by SaraPiccolomini** [SaraPiccolomini/Visualeyed#6]
- [x] Landing > box bianco dovrebbe essere di forma quadrata (il box dell'artciolo prende l'altezza del quadrato bianco)
<img width="1569" alt="Schermata 2020-10-23 alle 15 45 53" src="https://user-images.githubusercontent.com/36152555/97011568-21458e80-1547-11eb-9e47-90fc52f2dad2.png">

- [x] pagina aggregazione Editor's Review > aumentare distanza tra gli articoli
<img width="1688" alt="Schermata 2020-10-23 alle 15 25 47" src="https://user-images.githubusercontent.com/36152555/97009295-379e1b00-1544-11eb-91fc-33ba3eb731b4.png">

- [x] Il topic non è presente nelle Editor' review
<img width="1585" alt="Schermata 2020-10-23 alle 15 28 43" src="https://user-images.githubusercontent.com/36152555/97009552-82b82e00-1544-11eb-9b5a-c3edc0679645.png">

- [x] è possibile sistemare il gradiente in modo da non distinguere lo sfondo della stellina dal border del box? Forse con un gradiente orizzontare (rosso a sx e blu a dx) invece che verticale
<img width="686" alt="Schermata 2020-10-23 alle 15 48 53" src="https://user-images.githubusercontent.com/36152555/97011908-8c8f6080-1547-11eb-8c7c-10f0c5994c5e.png">

- [x]  Non trovo questa formattazione dell'articolo per le editor's review
https://app.zeplin.io/project/5f6223886e8ac3a4859791b8/screen/5f6225664581c8a825679bc7/
<img width="249" alt="Schermata 2020-10-23 alle 15 33 50" src="https://user-images.githubusercontent.com/36152555/97010081-40432100-1545-11eb-843d-38609317011d.png">

- [x] è possibile scrivere da CMS la descrizione dei vari articoli? In questo momento prende il sottotitolo dell'articolo mentre a noi servirebbe poter fare una vera e propria "review" di ciascun articolo.
<img width="877" alt="Schermata 2020-10-26 alle 13 35 45" src="https://user-images.githubusercontent.com/36152555/97173120-598bdd80-1790-11eb-9906-27202545296c.png">

**Comment by francescocusmai** [comment]
"è possibile scrivere da CMS la descrizione dei vari articoli? In questo momento prende il sottotitolo dell'articolo mentre a noi servirebbe poter fare una vera e propria "review" di ciascun articolo."

Ho aggiunto nel CMS > Articles un tab per editare la "review" che adesso viene visualizzata al posto dell'articolo nelle Editor's Review.

<img width="1162" alt="Schermata 2020-10-26 alle 18 29 42" src="https://user-images.githubusercontent.com/73244274/97206764-75f04000-17b9-11eb-992a-55ddf0b338ec.png">

**Comment by SaraPiccolomini** [comment]
purtroppo non riusciamo a capire come mettere la descrizione per ciascun articolo, 
abbiamo provato a mettere del testo in review ma non lo carica, 
stiamo sbagliando qualcosa? 

Lo vediamo così ma vorremmo aggiungere la descrizione per ciascuno dei tre articoli

<img width="850" alt="Schermata 2020-10-28 alle 12 09 18" src="https://user-images.githubusercontent.com/36152555/97428569-7520f080-1916-11eb-9f42-0980e4d746e9.png">

**Comment by francescocusmai** [comment]
Ho fatto una prova e mi sembra che funzioni correttamente. Provo a darvi indicazioni più precise:

1) Nell'articolo "Translating Covid-19 into visual stories" avete collegato gli Articoli ID: 346, 342, 340
2) Ciasuno di questi articoli dovrebbero avere una review associata

Ad esempio, ho aggiunto una review per l'articolo ID 346 ("How Long Will a Vaccine Really Take?") la review viene visualizzata correttamente nell'articolo  "Translating Covid-19 into visual stories" (vedi screenshot).

<img width="1175" alt="Schermata 2020-10-28 alle 16 03 28" src="https://user-images.githubusercontent.com/73244274/97455325-05236200-1938-11eb-898a-6f4e3fe24bd7.png">
<img width="1175" alt="Schermata 2020-10-28 alle 16 03 09" src="https://user-images.githubusercontent.com/73244274/97455337-094f7f80-1938-11eb-8249-89d9a1653ead.png">
<img width="1175" alt="Schermata 2020-10-28 alle 16 02 18" src="https://user-images.githubusercontent.com/73244274/97455352-0c4a7000-1938-11eb-9a05-c33fe639efe2.png">

Avvisatemi se qualcosa non dovesse essere chiaro.

**Comment by SaraPiccolomini** [comment]
Perfetto, funziona! Grazie mille per la spiegazione!
