### ISSUE TITLE
Web's Finest

### ISSUE THREAD

**Issue by SaraPiccolomini** [SaraPiccolomini/Visualeyed#8]
- [x] Landing > Must Read > no testo per articolo in highlight
<img width="929" alt="Schermata 2020-10-23 alle 15 40 06" src="https://user-images.githubusercontent.com/36152555/97010744-1fc79680-1546-11eb-8464-75eb8830ac20.png">

- [x] Label autori > diminuire padding top e bottom
<img width="1720" alt="Schermata 2020-10-23 alle 15 38 00 copia" src="https://user-images.githubusercontent.com/36152555/97010696-0de5f380-1546-11eb-90d8-722ca0edf9e0.png">

- [x] è possibile inserire la montly selection in mezzo al flusso degli articoli e non per forza come ultimo elemento?
<img width="951" alt="Schermata 2020-10-23 alle 15 42 53" src="https://user-images.githubusercontent.com/36152555/97011091-8cdb2c00-1546-11eb-80e8-640ef4c151b3.png">

- [x] mobile > allineamento immagine nel cerchio deve essere 
<img width="1126" alt="Schermata 2020-10-23 alle 17 16 23" src="https://user-images.githubusercontent.com/36152555/97022065-f44ba880-1553-11eb-8ccc-0d8502a60b89.png">
allineata a destra

**Comment by francescocusmai** [comment]
"è possibile inserire la montly selection in mezzo al flusso degli articoli e non per forza come ultimo elemento?"

Purtroppo non è una cosa semplice da gestire. Il flusso degli articoli e il box laterale "Climate Changes" sono su due colonne diverse mentre il box "Monthly Selection" si estende su entrambe le colonne. Eventualmente su questo punto sentiamoci.

**Comment by SaraPiccolomini** [comment]
Se invece il box "monthly selection" fosse della stessa larghezza del flusso degli articoli (quindi con solo due articoli, oppure 4) sarebbe più semplice?

Se anche così resta di difficile realizzazione possiamo lasciarlo così.

**Comment by francescocusmai** [comment]
Se gli diamo la stessa larghezza del flusso degli articoli non dovrebbero esserci problemi. Procedo in questo modo e vediamo come viene.

**Comment by SaraPiccolomini** [comment]
Abbiamo fatto un confronto su questo io e Tommaso e ci convinceva di più quando il box si estendeva su entrambe le colonne. Scusaci per il rework!
Possiamo tornare alla versione precedente? Nessun problema se così facendo il box risulterà in fondo al flusso degli articoli!

La distanza tra titolo "our montly selection" e gli articoli è eccessiva
